export const dummyData = [
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Man",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Man",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Man",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Man",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Man",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Man",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
    {
        geslacht: "Vrouw",
        leeftijd: 36,
        bmi: 22,
        asa: 3,
        operatieduur: 87,
        opnameduur: 93,
        aantal_medicijnen: 24,
        aantal_diagnoses: 15,
        veilig_ontslag: "Ja",
        certaintyscore: 83
    },
]